### ISSUE TITLE
Support :foreign-libs

### ISSUE THREAD

**Issue by martinklepsch** [cljsjs/boot-cljsjs#19]
- [x] add `deps.cljs` file to all jars.
   - [x] jquery
   - [x] hammer
   - [x] moment
   - [x] react
   - [x] react with add ons
   - [x] jquery datepicker
   - [x] pikaday
- [x] create simple testbed that calls a function of each lib after advanced compilation
   - [x] jquery
   - [x] hammer
   - [x] moment
   - [x] react
   - [x] react with add ons
   - [x] jquery datepicker
   - [x] pikaday
- [x] publish all jars
   - [x] jquery
   - [x] hammer
   - [x] moment
   - [x] react
   - [x] react with add ons
   - [x] jquery datepicker
   - [x] pikaday
- [x] update `boot-cljs` to newest Clojurescript
- [x] deprecate `from-cljsjs` task. (not mentioned anymore)
- [x] update documentation (packages & boot-cljsjs)

**Comment by martinklepsch** [comment]
@Deraen tracking progress here, just so you know :)

**Comment by Deraen** [comment]
Moment and Pikaday are published to Clojars.

I think it would be reasonable to push package changes to master... mostly because push-release refuses to work if branch is not named master.

**Comment by martinklepsch** [comment]
you can disable that with
```
(task-options! push {:ensure-clean  false
                                 :ensure-branch nil
                                 :ensure-tag    (last-commit)})
```
or something along those lines

**Comment by martinklepsch** [comment]
I created some sort of testbed here: https://github.com/cljsjs/testbed
Currently the multiple builds functionality of boot-cljs is broken by `0.0-2727` but I hope in the future this might be a nice way to do some basic smoke tests.

Testing Pikaday, the daterange-picker and react with addons requires separate html files and will currently not work due to the issue mentioned above.
