### ISSUE TITLE
"/js" added twice to included files path

### ISSUE THREAD

**Issue by nblumoe** [cljsjs/boot-cljsjs#20]
The script tags added to `index.html` have one `/js` too much:
![hi__world_](https://cloud.githubusercontent.com/assets/995628/5891430/6dee01be-a495-11e4-8257-e148860da8bc.png)

The path should be `/js/react.inc.js`, that's where the file actually resides on the filesystem and should be reached by the webserver. So the file resides in the right place, but a wrong path ends up in `adzerk.boot-cljs.middleware/write-src` I'd think.

It's reproducible in a fresh app created with tenzing (https://github.com/martinklepsch/tenzing) via `lein new tenzing broken-app +reagent` and running `boot dev`.

I also tried downgrading boot-cljsjs, as there has been a recent change on the paths handling (https://github.com/cljsjs/boot-cljsjs/commit/f277193738f77865bbc1fe84cd4ae6dc325fd06d), but the problem also existed on v0.3.1.

**Comment by martinklepsch** [comment]
Hey, thanks for the report.
This was a regression in `boot-cljs` which I tried to fix but seemingly my fix had some issues: https://github.com/cljsjs/boot-cljsjs/issues/18. I just pushed a new version of tenzing that uses `[adzerk/boot-cljs      "0.0-2629-9"]` which should include my broken fix so you'll probably end up at the same place as in the linked issue above.
