### ISSUE TITLE
Add support to externs free libraries

### ISSUE THREAD

**Issue by jeluard** [cljsjs/boot-cljsjs#23]
Some libraries do not need `externs` to properly work. A canonical example is a polyfill library whose associated `externs` are already in closure compiler.

Let me know if this is desirable. I have a patch for this.

**Comment by martinklepsch** [comment]
Good point. What kind of patch do you have in mind?

**Comment by jeluard** [comment]
Simply removing the check on `externs` and not including it in `deps.cljs`. It appears to work fine. Am I missing something?

**Comment by martinklepsch** [comment]
Maybe we should introduce a flag `--no-externs` so we it's a little more explicit and we still keep the validation helpers for the common case of packaging libs with extern files?

**Comment by jeluard** [comment]
Sounds good I'll do that.
