### ISSUE TITLE
Supporting `:module-type` compiler option

### ISSUE THREAD

**Issue by shaunlebron** [cljsjs/boot-cljsjs#29]
I think it would be ideal to replace this (which doesn't even work on Node):

``` clj
(ns example.core
  (:require cljsjs.foo))

;; how to use in the Browser
(def foo js/foo)

;; how to use in Node (can't?)
(def foo (js/require "????"))  ;; content is unnamed somewhere in our compiled code
```

with this, by allowing an option [ `{:module-type :common-js}`](https://github.com/clojure/clojurescript/wiki/Compiler-Options#foreign-libs):

``` clj
(ns example.core
  (:require [cljs.foo :as foo])) ;; works in Browser and Node
```

This option enables us to have the Closure compiler transform the library into a Closure module, rather than just pasting the library into the compiled output.  Pending a future patch for a [bug](https://github.com/shaunlebron/umd-cljs-bug) found in this process, I think supporting this new `module-type` option would be nice.
## 

Background references:
- https://github.com/clojure/clojurescript/wiki/Google-Summer-of-Code-2015#module-support
- http://mneise.github.io/posts/2015-07-08-week-6.html

**Comment by martinklepsch** [comment]
@shaunlebron this sounds great, I assume this doesn't have any impact on externs (i.e. they're still required)?

**Comment by plexus** [comment]
Externs are no longer required in this case. The CommonJS/AMD/ES2015 module gets converted into a Google Closure Compiler module and can be consumed as such.

**Comment by Deraen** [comment]
Blocked by: http://dev.clojure.org/jira/browse/CLJS-1762 and probably other bugs will be found once Closure compiler has been updated.

**Comment by kommen** [comment]
Now that there's `:module-type` support in ClojureScript since 1.9.454 (https://clojurescript.org/reference/javascript-module-support) would the be interest to support this option in cljsjs?

**Comment by Deraen** [comment]
Closure/ClojureScript doesn't currently support Node module resolution in classpath (e.g. Cljsjs JARs). Either files would need to be copied to filesystem in Cljs compiler, or something (Cljs, Cljsjs) should provide Closure node module resolution implementation which works with classpath.

**Comment by kommen** [comment]
I see, thanks.

**Comment by flyboarder** [comment]
Does the `:npm-deps` option solve this now?

**Comment by Deraen** [comment]
It doesn't solve this, it works around this.

I'd still prefer solution which doesn't involve calling `npm` and instead packages the files to JARs.

**Comment by Deraen** [comment]
Also, when using `:npm-deps`, it doesn't make much sense to provide those in separate package, it is easy for user to declare `:npm-deps` in the project. But for this use case we could provide separate externs packages.

**Comment by Deraen** [comment]
I don't think there is anything to do related to Cljsjs here. Deps.cljs can be generated with `:module-type` entries, but I think ClojureScript compiler and Closure only work if those files are available in filesystem, not classpath. This will need to be fixed elsewhere.
