### ISSUE TITLE
Smoke-test externs syntax at build time

### ISSUE THREAD

**Issue by martinklepsch** [cljsjs/boot-cljsjs#32]
This could be done by compiling a minimal project with the supplied externs (probably cljs isn't even needed). The result would be that syntax errors in externs and duplicate declarations are catched at build time compared to run time.

via https://github.com/cljsjs/packages/issues/508

**Comment by Deraen** [comment]
This is implemented by https://github.com/cljsjs/packages/blob/master/test-extern-files.sh which is running on CircleCI.
