### ISSUE TITLE
from-cljsjs should have a target option

### ISSUE THREAD

**Issue by martinklepsch** [cljsjs/boot-cljsjs#6]

**Comment by Deraen** [comment]
Probably not needed?

**Comment by martinklepsch** [comment]
When using :none I would think that you want to make sure it's in public/
(if applicable). I think that was what I had in mind when filing that
issue.

Might be totally wrong though, things have been changing fast recently :)

On Saturday, January 3, 2015, Juho Teperi <notifications@github.com> wrote:

> Probably not needed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cljsjs/boot-cljsjs/issues/6#issuecomment-68606125>.
>


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>

**Comment by Deraen** [comment]
Yeah this would probably be wrong solution for that problem.

**Comment by martinklepsch** [comment]
Isn't that exactly what target is meant for in those other tasks?

>

-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>

**Comment by Deraen** [comment]
Yeah. That might also be wrong solution.

Rc5 will include improved sift task which can be used to move stuff around inside filset.
Sift could also in future support adding files from jars to fileset, making `from-jars` and possible `from-webjars` unnecessary.
