### ISSUE TITLE
it is valid for :global-exports key to be a string

### ISSUE THREAD

**Issue by henryw374** [cljsjs/boot-cljsjs#60]
the deps-cljs task specs global-exports as a map of {sym sym}, but I think keys ought to be able to be strings as well. see https://clojure.atlassian.net/browse/CLJS-3138 

Error:
```
option :global-exports must be of type {sym sym}
```

**Comment by Deraen** [comment]
Global-exports task option is deprecated, use foreign-libs option instead:

https://github.com/cljsjs/boot-cljsjs/blob/master/src/cljsjs/boot_cljsjs/packaging.clj#L208
https://github.com/cljsjs/packages/blob/master/react-sortable-hoc/build.boot#L27-L34

**Comment by henryw374** [comment]
thanks
