### ISSUE TITLE
Be clear when things are added to fileset

### ISSUE THREAD

**Issue by martinklepsch** [cljsjs/boot-cljsjs#9]
Currently there are no messages when things are added to the fileset.
When adding files to the fileset the user should be notified about this at least on the initial compilation cycle.

**Comment by Deraen** [comment]
https://github.com/cljsjs/boot-cljsjs/blob/master/src/cljsjs/boot_cljsjs.clj#L19 ?

**Comment by martinklepsch** [comment]
@Deraen nevermind :D
